# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: 
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: docs-assistant
service: campus-docs-assistant  # Service name

provider:
  name: aws
  region: us-east-1
  stage: dev
  runtime: python3.12
  iamRoleStatements:
    - Effect: Allow
      Action:
        - rekognition:SearchFacesByImage
        - rekognition:DetectFaces
        - rekognition:CreateCollection
        - rekognition:IndexFaces
        - rekognition:ListCollections
        - rekognition:DeleteCollection
        - bedrock:InvokeModel
        - polly:SynthesizeSpeech
        - lex:RecognizeText
        - lex:DeleteSession
        - lex:GetSession
        - lex:PutSession
        - s3:GetObject
        - s3:PutObject
        - dynamodb:DescribeTable
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:createTable
        - lambda:InvokeFunction
        - sqs:SendMessage
        - sqs:GetQueueUrl
      Resource: "*"

functions:
  telegramToLex:
    handler: handler.telegramToLex_handler
    timeout: 30
    events:
      - httpApi:
          path: /telegram-webhook
          method: post
